### ISSUE TITLE
Roadmap for aloft data

### ISSUE THREAD

**Issue by peterdesmet** [enram/aloftdata.eu#1]
As discussed with @CeciliaNilsson709 this is the envisioned roadmap for the aloftdata.eu website

## Website

- [x] Homepage: explains scope "Bird movement data from European weather radars" and has quick links to visualize (see #3 for more tasks)
- [x] Visualize: CROW visualization for BALTRAD data (external page)
- [x] Browse: file navigation for BALTRAD data (JS on top of S3 repo)
- [x] Datasets: More technical instructions on how to download BALTRAD data. Can be extended with other technical pages for other datasets (see #6 for more tasks)
- [x] About: About page for the website, includes FAQ for non-technical users (see #7 for more tasks)
- [x] Radars (optional): Overview of European radars + metadata **TODO: useful?** yes

## GitHub repositories

This is where the code would live for different components

- [x] `enram/aloftdata.eu` (Jekyll): home of the aloftdata website
- [x] `enram/data-repository` (Python): (same as current situation): code for getting data onto the data repository + issues regarding data quality. Landing `index.html` page would move to `enram/aloftdata.eu`
- [x] `enram/crow` (Vue): home of the crow visualization for aloft (currently BALTRAD data only). Would mimic aloftdata style
- [x] `enram/vpts` (Jekyll): keep has home for vpts csv format, but remove website and integrate directly in aloftdata.eu/format/vpts

## URLs and names

- [x] http://enram.github.io/aloftdata.eu redirect to (CNAME) https://aloftdata.eu
- [x] http://enram.github.io/data-repository redirects to https://aloftdata.eu/browse
- [x] Test if http://enram.github.io/data-repository/?prefix=se/osd/ has a meaningful redirect (no, but that's fine)
- [x] http://enram.github.io/crow (new) redirects to https://aloftdata.eu/crow or https://crow.aloftdata.eu
- [x] ENRAM data repository -> Aloft data portal
