### ISSUE TITLE
Website/homepage todo

### ISSUE THREAD

**Issue by peterdesmet** [enram/aloftdata.eu#3]
- [x] Write content for homepage
- [x] Provide link for "radar aeroecology community"
- [x] Choose home banner (originally [home-banner](https://user-images.githubusercontent.com/600993/181777440-b3ed2e93-2274-4b06-99ba-3c3a8bc4781b.png))
- [x] Save home banner locally
- [ ] Add favicon?
- [ ] Add banner logo?
- [x] Add images on homepage for quick navigation? (see template below)

**Comment by peterdesmet** [comment]
Template created for having images on homepage:

```HTML
---
layout: base
description: Template for homepage, adapted from petridish _layout/home.html
remark: See also page.layout == 'home' in head.html and header.html
---
<div class="row">
  <div class="col-md-10 col-lg-8 mx-auto">
    <div class="row">
      <div class="col">
        {{ content }}
      </div>
    </div>
    
    {% if site.pages_on_home %}
      <div class="row cards mt-4">
        {% for page_name in site.pages_on_home %}
          {% assign post = site.pages | where: "name", page_name | first %}
            {% if post %}
            <div class="col-md-6{% if twitter_feed %} col-lg-4{% endif %}">
              {% include card.html %}
            </div>
          {% endif %}
        {% endfor %}
      </div>
    {% endif %}
</div>
```

**Comment by peterdesmet** [comment]
Updated at https://aloftdata.eu/. No logo or favicon for now.
